runtime: python311
instance_class: B8
env_variables:
  GEOAPIFY_API_KEY: "1df139ec70004766b20c761c341b5019"
  CUMTD_API_KEY: "81a29848fd1f428894c9b8331df94c53"
  MAP_KEY: "AIzaSyBtBVVS6-Ru8rpYaaoL-gOtmTO3rPStwlI"
basic_scaling:
  max_instances: 4 # maximum number of instances based on traffic
  idle_timeout: 10m
